apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsku-deploy
spec:
  selector:
    matchLabels:
      app: appsku
  template:
    metadata:
      labels:
        app: appsku
    spec:
      containers:
      - name: ct-appsku
        image: galawana/apps-2048:v0.1
        ports:
        - containerPort: 80
